---
name: CI

on: [ push ]
jobs:
  build-java:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        javaVersion: [ "11", "17", "21" ]
        javaDistribution: 
          - corretto
          - liberica
          - microsoft
          - temurin
          - zulu
    name: Java ${{ matrix.javaVersion }}-${{ matrix.javaDistribution }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.javaDistribution }}
          java-version: ${{ matrix.javaVersion }}
          cache: 'maven'
      - run: mvn test --no-transfer-progress
