---
name: CI

on: [ push ]
jobs:
  build-java:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        javaVersion: [ "11", "17" ]
        javaDistribution: 
          - corretto
          - liberica
          - microsoft
          - temurin
          - zulu
    name: Java ${{ matrix.javaVersion }}-${{ matrix.javaDistribution }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.javaDistribution }}
          java-version: ${{ matrix.javaVersion }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn test --no-transfer-progress
